```{r}
## Ordinal endpoint distributions in both the placebo and IVIG groups on day 7
plac_prob = c(0.009852217,0.049261084,0.162561576,0.145320197,0.362068966,0.270935961)
exp_prob = c(0.005590184,0.028688675,0.104327684,0.108127134,0.356486213,0.396780110)

## p0 and p1 are the discharge probabilities on day 7 for placebo and treatment, respectively.
p0 = sum(plac_prob[5:6])

p1 = sum(exp_prob[5:6])

g0 = log(-log(1-p0)/7)
g1 = log(-log(1-p1)/7) - g0

plac_bin = c(p0,1-p0)
exp_bin = c(p1,1-p1)

n = 320
qc = qnorm(0.975)

ORfun = function(p0,OR){
	p0 = 1 - p0
	pexp = p0/(p0 + (1 - p0)*OR)
	return(1-pexp)
}

days = seq(1,14,0.5)
p3 = seq(0.01,0.99,0.01)
p3c = 1 - sum(((plac_bin + exp_bin)/2)^3)
res = NULL
p3dmat = NULL
for(i in 1:27){
	day = days[i]
	pd = pexp(day,exp(g0))
	pe = pexp(day,exp(g0+g1))
	p3d = p3[p3>p3c]

	pt1 = log(1.77) * sqrt(n^3*p3d/(12*(n+1)^2))
	
	t2 = log(log(1-pe)/log(1-pd)) * (2/n * (1/pd + 1/pe))^(-1/2)
	pt2 = rep(t2,length(p3d))

	x = length(pt1)
	repv = rep(NA,99-x)	

	p3dmat = cbind(p3dmat,c(p3d,repv))
	res = cbind(res,c(pt1,repv),c(pt2,repv),b=c(ifelse(pt1>pt2,1,0),repv))
}

ind = seq(3,81,3)
graph = NULL
for(i in 1:27){
	day = days[i]
	index = ind[i]
	graph = cbind(graph,day=rep(day,99),p3d = p3dmat[,i],b=res[,index])
}

zerosub = NULL
for(i in 1:27){
	index = ind[i]
	subgraph = as.data.frame(graph[,c((index-2):index)])
	sub = subset(subgraph,subgraph$b == 0)
	zerosub = rbind(zerosub,sub)
}

onesub = NULL
for(i in 1:27){
	index = ind[i]
	subgraph = as.data.frame(graph[,c((index-2):index)])
	sub = subset(subgraph,subgraph$b == 1)
	onesub = rbind(onesub,sub)
}

daysub = NULL
minsub = NULL
maxsub = NULL
for(i in 1:27){
	daysub = subset(onesub, day == days[i])
	minsub = rbind(minsub,c(days[i],min(daysub$p3d)))
	maxsub = rbind(maxsub,c(days[i],max(daysub$p3d)))
}

daysub2 = NULL
minsub2 = NULL
maxsub2 = NULL
for(i in 1:17){
	daysub2 = subset(zerosub, day == days[i+10])
	minsub2 = rbind(minsub2,c(days[i+10],min(daysub2$p3d)))
	maxsub2 = rbind(maxsub2,c(days[i+10],max(daysub2$p3d)))
}

par(mar=c(5,6,4,2))
term = expression(1 - sum(bar(p)[i]^3,i==1,k))
plot(x=1,y=1,xlab = "Day of Evaluation",ylab = term, xlim = c(1,14),
	ylim = c(0,1),type="n",xaxt = "n", yaxt = "n")
polygon(c(minsub[,1],rev(maxsub[,1])),c(minsub[,2],maxsub[,2]),
	col='blue',border='green')
polygon(c(rev(maxsub2[,1]),minsub2[,1]),c(minsub2[,2],maxsub2[,2]),
	col='red',border='yellow')
points(7,1 - sum(((plac_prob + exp_prob)/2)^3),pch = 16, col = 'purple')

axis(1, at=c(1,14), labels=c("",""), lwd.ticks=0)
axis(1, at=seq(1,14,by=1), lwd=0, lwd.ticks=1)
axis(2, at=c(0,1), labels=c("",""), lwd.ticks=0)
axis(2, at=seq(0,1,0.1), lwd=0, lwd.ticks=1)
```

```{r}
p0s = seq(0.01,0.99,0.01)
p3 = seq(0.01,0.99,0.01)
res = NULL
p3dmat = NULL
for(i in 1:99){
	p0d = p0s[i]
	p0e = ORfun(p0d,1.77)
	p3c = 1 - ((p0d+p0e)/2)^3 - ((2-p0d-p0e)/2)^3
	p3d = p3[p3>p3c]

	pt1 = log(1.77) * sqrt(n^3*p3d/(12*(n+1)^2))

	t2 = log(log(1-p0e)/log(1-p0d)) * (2/n * (1/p0d + 1/p0e))^(-1/2)
	pt2 = rep(t2,length(p3d))

	x = length(pt1)
	repv = rep(NA,99-x)	

	p3dmat = cbind(p3dmat,c(p3d,repv))
	res = cbind(res,c(pt1,repv),c(pt2,repv),b=c(ifelse(pt1>pt2,1,0),repv))	
}

ind = seq(3,297,3)
graph = NULL
for(i in 1:99){
	p0d = p0s[i]
	index = ind[i]
	graph = cbind(graph,p0d=rep(p0d,99),p3d = p3dmat[,i],b=res[,index])
}

zerosub = NULL
for(i in 1:99){
	index = ind[i]
	subgraph = as.data.frame(graph[,c((index-2):index)])
	sub = subset(subgraph,subgraph$b == 0)
	zerosub = rbind(zerosub,sub)
}

onesub = NULL
for(i in 1:99){
	index = ind[i]
	subgraph = as.data.frame(graph[,c((index-2):index)])
	sub = subset(subgraph,subgraph$b == 1)
	onesub = rbind(onesub,sub)
}

p0sub = NULL
minsub = NULL
maxsub = NULL
for(i in 1:99){
	p0sub = subset(onesub, p0d == p0s[i])
	minsub = rbind(minsub,c(p0s[i],min(p0sub$p3d)))
	maxsub = rbind(maxsub,c(p0s[i],max(p0sub$p3d)))
}

p0sub2 = NULL
minsub2 = NULL
maxsub2 = NULL
for(i in 1:63){
	p0sub2 = subset(zerosub, p0d == p0s[i+36])
	minsub2 = rbind(minsub2,c(p0s[i+36],min(p0sub2$p3d)))
	maxsub2 = rbind(maxsub2,c(p0s[i+36],max(p0sub2$p3d)))
}

par(mar=c(5,6,4,2))
term = expression(1 - sum(bar(p)[i]^3,i==1,k))
term2 = expression(paste("Placebo Group Probability of Discharge at Evaluation ",
	 (p[0])))
plot(x=1,y=1,ylab = term, xlab = term2, 
	xlim = c(0,1),ylim = c(0,1),type="n",xaxt = "n",yaxt="n")
polygon(c(minsub[,1],rev(maxsub[,1])),c(minsub[,2],maxsub[,2]),
	col='blue',border='green')
polygon(c(rev(maxsub2[,1]),minsub2[,1]),c(rev(minsub2[,2]),maxsub2[,2]),
	col='red',border='yellow')
points(p0,1 - sum(((plac_prob + exp_prob)/2)^3),pch = 16, col = 'purple')

axis(1, at=c(0,1), labels=c("",""), lwd.ticks=0)
axis(1, at=seq(0,1,0.1), lwd=0, lwd.ticks=1)
axis(2, at=c(0,1), labels=c("",""), lwd.ticks=0)
axis(2, at=seq(0,1,0.1), lwd=0, lwd.ticks=1)
```